# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8f5c95e5ab3477eb46e50bbb56f9d4e1a0413aaa347a16fe69bf890f849f12b7b237dcb5dd229be0a4b5e1e89e511a70ad8624d6a8f23c2e8a99ec449438f86

test:
  secret_key_base: 14099d1c79e5c30ee118577c271893711de5cc233e4145a7861e7e0db59e3454b9f4f055e5012013f104c99dad78b967d1f6f5f4b56ab05e9bfbc50551700a25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
